modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "resourcefulcreepers"
version = "${version}"
displayName = "Resourceful Creepers"
authors = "CreeperHost"
description = '''
Backup all the things!
'''
#logoFile = ""

[[dependencies.resourcefulcreepers]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resourcefulcreepers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resourcefulcreepers]]
modId = "architectury"
mandatory = true
versionRange = "[5.5.16,)"
ordering = "AFTER"
side = "BOTH"
